Repository espressif/conventional-precommit-linter, pull requests merged in 2023-12, with the labels that each got.

#15 Fix partial match of the commit type
  conventional_precommit_linter/hook.py
  tests/test_default_args.py
Labels: Type: Bug

#17 ci: add PR linter Danger + Contributings Guide
  .github/workflows/dangerjs.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
Labels: Type: Doc, Status: Reviewing

#14 Add support for optional `!` in commit type
  .gitignore
  README.md
  conventional_precommit_linter/hook.py
  tests/conftest.py
  tests/test_custom_args.py
  tests/test_default_args.py
Labels: Type: Feature Request, Status: Reviewing
